<?php

/**
 * Демонстрация контроллера для полученяи списка ресурсов
 */
class CrontabControllerDemoList extends modCrontabController
{
    public $classKey = 'modResoruce';

    protected function prepareListQueryBeforeCount(xPDOQuery $c)
    {
        $c->where([
            'published' => true
        ]);
        return parent::prepareListQueryBeforeCount($c); // TODO: Change the autogenerated stub
    }

    protected function prepare($object)
    {
        echo '<pre>';
        print_r($object->toArray());
        die;
        parent::prepare($object); // TODO: Change the autogenerated stub
    }
}
