<?php
if (!class_exists('CrontabManagerManual')) {
    include_once dirname(dirname(dirname(__FILE__))) . '/model/crontabmanagerhandler.class.php';
}

class CrontabManagerHandlerFile extends CrontabManagerHandler implements CrontabManagerHandlerInterface
{
    protected $loadClass = 'File';

    public function initialize()
    {
        $response = parent::initialize(); // TODO: Change the autogenerated stub
        if ($response) {
            // С крон заданиями в для класса
            $crontabs = $this->CrontabManager->config['schedulerPath'] . '/crontabs';
            if (!file_exists($crontabs)) {
                if (!mkdir($crontabs, 0777, true)) {
                    $this->modx->log(modX::LOG_LEVEL_ERROR, "Error create dir {$crontabs}", '', __METHOD__, __FILE__, __LINE__);
                    $response = false;
                }
            }
        }
        return $response;
    }
}
